version: "3"

services:
  server:
    build: .
    restart: always
  proxy:
    dockerfile: ./proxy/Dockerfile
    build: ./proxy/.
    restart: always
    depends_on: 
      - server
    volumes:
      - ./proxy/cert:/cert