version: "3"

services:
  server:
    build: .
    restart: always
  proxy:
    build:
      context: proxy/.
      dockerfile: proxy/Dockerfile
    restart: always
    depends_on: 
      - server
    volumes:
      - ./proxy/cert:/cert