version: "3"

services:
  server:
    build: .
    restart: always
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  proxy:
    build:
      context: ./proxy/.
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on: 
      - server
      - certbot
    volumes:
      - ./proxy/cert:/cert
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"